

CREATE TABLE userinfo (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    description text,
    profile_image_url varchar(100),
    followers_count integer

);


CREATE TABLE reviews (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    points int,
    title text,
    description text,
    taster_name varchar(100),
    taster_twitter_handle varchar(100),
    price int,
    designation varchar(100),
    variety varchar(100),
    region_1 varchar(100),
    region_2 varchar(100),
    province varchar(100),
    country varchar(100),
    winery varchar(100)
);

