

CREATE TABLE userinfo (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50),
    description text,
    profile_image_url varchar(50),
    followers_count integer

);


CREATE TABLE reviews (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    points int,
    title varchar(50),
    description varchar(50),
    taster_name varchar(50),
    taster_twitter_handle varchar(50),
    price int,
    variety varchar(50),
    region_1 varchar(50),
    region_2 varchar(50),
    province varchar(50),
    country varchar(50),
    winery varchar(50)
);

